site_name: Editor do Guia de Serviços
pages:
- [index.md, Principal]
- ['sobre/links.md', 'Sobre o projeto', 'Referências']
- ['sobre/autores.md', 'Sobre o projeto', 'Autores']
- ['sobre/contato.md', 'Sobre o projeto', 'Contato']
- ['sobre/license.md', 'Sobre o projeto', 'Licença']

theme: readthedocs
repo_url: https://github.com/servicosgovbr/editor-guia-de-servicos
markdown_extensions: [admonition]
