spring:
  thymeleaf:
    cache: true

endpoints:
  enabled: false

  jolokia:
    enabled: false

flags:
  importar.cartas: false

eds:
  cartas:
    repositorio: "https://github.com/servicosgovbr/cartas-de-servico.git"