spring:
  main:
    show-banner: false

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres

security:
  ignored:
    - '/editar/info'
    - '/editar/health'
    - '/editar/assets/**'
    - '/editar/fonts/**'

endpoints:
  health:
    sensitive: false

server:
  port: ${port:8090}

management:
  context-path: /editar

flags:
  git.push: true
  esquentar.cache: true
  importar: true

eds:
  cartas:
    repositorio: "https://github.com/servicosgovbr/cartas-de-teste.git"

---

spring:
  profiles: desenvolvimento,teste

  datasource:
    url: jdbc:h2:mem:editor