spring:
  main:
    show-banner: false

  thymeleaf:
    cache: false

server:
  port: ${port:8080}

flags:
  importar.cartas: false

eds:
  cartas:
    repositorio: "https://github.com/servicosgovbr/cartas-de-servico.git"