spring:
  main:
    show-banner: false

  thymeleaf:
    cache: false

server:
  port: ${port:8090}

management:
  context-path: /editar

flags:
  importar.cartas: true
  git.push: false

eds:
  cartas:
    repositorio: "https://github.com/servicosgovbr/cartas-de-servico.git"